[package]
name = "minesweeper-rs"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2021"

[dependencies]
rand = "0.9"
windows-composition = { git = "https://github.com/microsoft/windows-rs", rev = "fa5059c3e7462ce66982ff7b9c523fae55b9d189" }
windows-window = { git = "https://github.com/microsoft/windows-rs", rev = "fa5059c3e7462ce66982ff7b9c523fae55b9d189" }

[features]
show-mines = []
