fn main() {
    windows::build!(
        windows::foundation::numerics::{Vector2, Vector3},
        windows::foundation::TimeSpan,
        windows::graphics::SizeInt32,
        windows::system::DispatcherQueueController,
        windows::ui::composition::{
            AnimationIterationBehavior,
            CompositionBatchTypes,
            CompositionBorderMode,
            CompositionColorBrush,
            CompositionGeometry,
            CompositionShape,
            CompositionSpriteShape,
            Compositor,
            ContainerVisual,
            SpriteVisual,
            CompositionEllipseGeometry,
            CompositionContainerShape,
            CompositionShapeCollection,
            VisualCollection,
            ShapeVisual,
            CompositionScopedBatch,
            Vector3KeyFrameAnimation,
            CompositionAnimation,
            CompositionNineGridBrush ,
        },
        windows::ui::composition::desktop::DesktopWindowTarget,
        windows::ui::{Colors, Color},
        windows::win32::system_services::CreateDispatcherQueueController,
        windows::win32::winrt::{ICompositorDesktopInterop},
    );
}
